CREATE TABLE `data_model` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SOURCE_NAME` varchar(100) DEFAULT NULL,
  `TRANSACTION_TYPE` varchar(50) DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `STATUS` varchar(100) DEFAULT NULL,
  `destination_name` varchar(255) DEFAULT NULL,
  `TRANSACTION_ID` int DEFAULT NULL,
  `SIDE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;